name: Verify Signatures with Gitsign

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Build project
      run: |
        mkdir -p dist
        echo "Example artifact" > dist/artifact.txt

    - name: Install Gitsign
      shell: bash
      run: |
        set -ex
        curl -fsL https://cli-server-trusted-artifact-signer.apps.rosa.ifiz9-9phbw-9fw.i5ut.p3.openshiftapps.com/clients/linux/gitsign-amd64.gz -o /usr/local/bin/gitsign-amd64.gz
        gunzip /usr/local/bin/gitsign-amd64.gz
        chmod +x /usr/local/bin/gitsign-amd64
        mv /usr/local/bin/gitsign-amd64 /usr/local/bin/gitsign

    - name: Initialize Gitsign
      shell: bash
      run: gitsign initialize --mirror=https://tuf-openshift-operators.apps.rosa.ifiz9-9phbw-9fw.i5ut.p3.openshiftapps.com --root=https://tuf-openshift-operators.apps.rosa.ifiz9-9phbw-9fw.i5ut.p3.openshiftapps.com/root.json

    - name: Verify Gitsign Installation
      run: |
        which gitsign
        ls -l /usr/local/bin/gitsign
        gitsign version
      shell: bash

    - name: Setup signing
      shell: bash
      run: |
        git config --global commit.gpgsign true
        git config --global gpg.x509.program gitsign
        git config --global gpg.format x509

    - name: Verify Commit Signatures
      run: |
        gitsign verify --certificate-identity=rachelyordan@gmail.com --certificate-oidc-issuer=token.actions.githubusercontent.com HEAD
      shell: bash

